[package]
edition = "2021"
name = "monet"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.14.1"
bevy_egui = "0.28.0"
